### ISSUE TITLE
Fatal Erro when pick +7 contacts

### ISSUE THREAD

**Issue by weslleyng** [xbroak/MultiContactPicker#1]
`
 FATAL EXCEPTION: main
                                                                             Process: br.com.apppacke, PID: 22203
                                                                             java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.wafflecopter.multicontactpicker.ContactResult)
                                                                                 at android.os.Parcel.writeSerializable(Parcel.java:1527)
                                                                                 at android.os.Parcel.writeValue(Parcel.java:1475)
                                                                                 at android.os.Parcel.writeList(Parcel.java:812)
                                                                                 at android.os.Parcel.writeValue(Parcel.java:1424)
                                                                                 at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
                                                                                 at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1417)
                                                                                 at android.os.Bundle.writeToParcel(Bundle.java:1157)
                                                                                 at android.os.Parcel.writeBundle(Parcel.java:764)
                                                                                 at android.content.Intent.writeToParcel(Intent.java:8703)
                                                                                 at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:3398)
                                                                                 at android.app.Activity.finish(Activity.java:5212)
                                                                                 at android.app.Activity.finish(Activity.java:5230)
                                                                                 at com.wafflecopter.multicontactpicker.MultiContactPickerActivity$2.onClick(MultiContactPickerActivity.java:79)
                                                                                 at android.view.View.performClick(View.java:5637)
                                                                                 at android.view.View$PerformClick.run(View.java:22433)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                              Caused by: java.io.NotSerializableException: android.net.Uri$StringUri
                                                                                 at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
                                                                                 at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
                                                                                 at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
                                                                                 at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
                                                                                 at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
                                                                                 at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
                                                                                 at android.os.Parcel.writeSerializable(Parcel.java:1522)
                                                                                 at android.os.Parcel.writeValue(Parcel.java:1475) 
                                                                                 at android.os.Parcel.writeList(Parcel.java:812) 
                                                                                 at android.os.Parcel.writeValue(Parcel.java:1424) 
                                                                                 at android.os.Parcel.writeArrayMapInternal(Parcel.java:724) 
                                                                                 at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1417) 
                                                                                 at android.os.Bundle.writeToParcel(Bundle.java:1157) 
                                                                                 at android.os.Parcel.writeBundle(Parcel.java:764) 
                                                                                 at android.content.Intent.writeToParcel(Intent.java:8703) 
                                                                                 at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:3398) 
                                                                                 at android.app.Activity.finish(Activity.java:5212) 
                                                                                 at android.app.Activity.finish(Activity.java:5230) 
                                                                                 at com.wafflecopter.multicontactpicker.MultiContactPickerActivity$2.onClick(MultiContactPickerActivity.java:79) 
                                                                                 at android.view.View.performClick(View.java:5637) 
                                                                                 at android.view.View$PerformClick.run(View.java:22433) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by xbroak** [comment]
Please try updating to the latest version, this should now be fixed! (1.2)
